import { useEffect, useState } from 'react';
import { Activity, RefreshCw } from 'lucide-react';
import { supabase } from '@/infrastructure/supabase/client';
import { PermissionGuard } from '@/core/permissions/PermissionGuard';

type HealthScore = { id: string; tenant_id: string; score_date: string; overall_score: number; login_frequency_score: number | null; activity_score: number | null; patient_growth_score: number | null; feature_adoption_score: number | null; revenue_trend_score: number | null; };

export default function GlobalHealthScores() {
  const [rows, setRows] = useState<HealthScore[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load = async () => { setLoading(true); setError(null); const {data,error:e}=await supabase.from('tenant_health_scores').select('id, tenant_id, score_date, overall_score, login_frequency_score, activity_score, patient_growth_score, feature_adoption_score, revenue_trend_score').is('deleted_at',null).order('score_date',{ascending:false}).limit(100); if(e){setError(e.message);setRows([]);} else setRows((data??[]) as HealthScore[]); setLoading(false); };
  useEffect(()=>{void load();},[]);
  return <PermissionGuard required="super_admin_access"><section className="space-y-4" dir="rtl"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Activity className="h-6 w-6 text-primary"/><div><h2 className="text-xl font-bold text-slate-900">درجات صحة العيادات</h2><p className="text-sm text-slate-500">واجهة مراقبة درجات الصحة حسب عقد Production الحالي.</p></div></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><RefreshCw className="h-4 w-4"/>تحديث</button></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">عقد RLS الحالي معزول حسب العيادة، لذلك لا يتم اختراع وصول عابر للـtenants داخل هذه الشاشة. يلزم عقد موثّق للعرض الشامل قبل فتحه.</div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white">{loading?<div className="p-6 text-sm text-slate-500">جاري التحميل...</div>:<table className="min-w-full text-sm"><thead className="bg-muted"><tr><th className="px-4 py-3 text-right">العيادة</th><th className="px-4 py-3 text-right">التاريخ</th><th className="px-4 py-3 text-right">الدرجة</th><th className="px-4 py-3 text-right">تسجيل الدخول</th><th className="px-4 py-3 text-right">النشاط</th><th className="px-4 py-3 text-right">نمو المرضى</th><th className="px-4 py-3 text-right">تبني الميزات</th><th className="px-4 py-3 text-right">اتجاه الإيرادات</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="px-4 py-3 font-mono text-xs">{r.tenant_id}</td><td className="px-4 py-3">{r.score_date}</td><td className="px-4 py-3 font-semibold">{r.overall_score}</td><td className="px-4 py-3">{r.login_frequency_score ?? '—'}</td><td className="px-4 py-3">{r.activity_score ?? '—'}</td><td className="px-4 py-3">{r.patient_growth_score ?? '—'}</td><td className="px-4 py-3">{r.feature_adoption_score ?? '—'}</td><td className="px-4 py-3">{r.revenue_trend_score ?? '—'}</td></tr>)}</tbody></table>}</div></section></PermissionGuard>;
}
