import { useEffect, useState } from 'react';
import { CheckCircle2, CreditCard, RefreshCw } from 'lucide-react';
import { supabase } from '@/infrastructure/supabase/client';
import { PermissionGuard } from '@/core/permissions/PermissionGuard';
import type { SubscriptionTier } from '@/shared/types/billing';

const TIERS: SubscriptionTier[] = ['trial','essential','professional','enterprise','suspended'];
const LABELS: Record<SubscriptionTier,string> = { trial:'تجريبي', essential:'أساسي', professional:'احترافي', enterprise:'مؤسسي', suspended:'موقوف' };
type Tenant = { id:string; clinic_name:string|null; clinic_name_ar:string|null; subscription_tier:SubscriptionTier };

export default function TierOverridePanel(){
 const [tenants,setTenants]=useState<Tenant[]>([]); const [notes,setNotes]=useState<Record<string,string>>({}); const [tiers,setTiers]=useState<Record<string,SubscriptionTier>>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError(null);const {data,error:e}=await supabase.from('master_tenants').select('id,clinic_name,clinic_name_ar,subscription_tier').is('deleted_at',null).order('clinic_name');if(e){setError(e.message);setTenants([]);}else{const rows=(data??[]) as Tenant[];setTenants(rows);setTiers(Object.fromEntries(rows.map(t=>[t.id,t.subscription_tier])));}setLoading(false);};
 useEffect(()=>{void load();},[]);
 const override=async(t:Tenant)=>{const newTier=tiers[t.id]??t.subscription_tier;const activationNotes=(notes[t.id]??'').trim();if(!activationNotes){setError('ملاحظات التفعيل إلزامية.');return;}setSaving(t.id);setError(null);setNotice(null);const {data:userData}=await supabase.auth.getUser();const userId=userData.user?.id;if(!userId){setError('جلسة المستخدم غير صالحة.');setSaving(null);return;}const {error:updateError}=await supabase.from('master_tenants').update({subscription_tier:newTier}).eq('id',t.id).is('deleted_at',null);if(updateError){setError(updateError.message);setSaving(null);return;}const {error:eventError}=await supabase.from('billing_events').insert({tenant_id:t.id,event_type:'tier_override_by_admin',previous_tier:t.subscription_tier,new_tier:newTier,is_manual:true,activated_by:userId,activation_notes:activationNotes});if(eventError){setError(eventError.message);}else{setNotice('تم تسجيل تجاوز الخطة في سجل الفوترة.');await load();}setSaving(null);};
 return <PermissionGuard required="super_admin_access"><section className="space-y-4" dir="rtl"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><CreditCard className="h-6 w-6 text-primary"/><div><h2 className="text-xl font-bold text-slate-900">تجاوزات الخطط</h2><p className="text-sm text-slate-500">تغيير الخطة مع تسجيل حدث إداري في سجل الفوترة.</p></div></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><RefreshCw className="h-4 w-4"/>تحديث</button></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white">{loading?<div className="p-6 text-sm text-slate-500">جاري التحميل...</div>:<table className="min-w-full text-sm"><thead className="bg-muted"><tr><th className="px-4 py-3 text-right">العيادة</th><th className="px-4 py-3 text-right">الخطة</th><th className="px-4 py-3 text-right">الملاحظات الإلزامية</th><th className="px-4 py-3 text-right">الإجراء</th></tr></thead><tbody className="divide-y divide-slate-100">{tenants.map(t=><tr key={t.id}><td className="px-4 py-3 font-medium">{t.clinic_name_ar||t.clinic_name||t.id}</td><td className="px-4 py-3"><select value={tiers[t.id]??t.subscription_tier} onChange={e=>setTiers(v=>({...v,[t.id]:e.target.value as SubscriptionTier}))} className="rounded-lg border border-slate-200 px-3 py-2">{TIERS.map(tier=><option key={tier} value={tier}>{LABELS[tier]}</option>)}</select></td><td className="px-4 py-3"><input value={notes[t.id]??''} onChange={e=>setNotes(v=>({...v,[t.id]:e.target.value}))} placeholder="سبب التجاوز" className="w-full min-w-[220px] rounded-lg border border-slate-200 px-3 py-2"/></td><td className="px-4 py-3"><button disabled={saving===t.id} onClick={()=>void override(t)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>{saving===t.id?'جاري الحفظ...':'تطبيق التجاوز'}</button></td></tr>)}</tbody></table>}</div></section></PermissionGuard>;
}
